#!/usr/bin/env bash
#
# bump-version.test.sh — bump-version.sh のテスト
#
# 実行: ./scripts/bump-version.test.sh
#
# 一時ディレクトリにサンプルのバージョンファイル群を再現し、
# bump-version.sh を適用して結果を検証する。

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_SCRIPT="$SCRIPT_DIR/bump-version.sh"

PASS=0
FAIL=0

assert_contains() {
  local file="$1" expected="$2" desc="$3"
  if grep -qF -- "$expected" "$file"; then
    echo "  OK: $desc"
    PASS=$((PASS + 1))
  else
    echo "  NG: $desc"
    echo "      期待値 \"$expected\" が $file に存在しません" >&2
    FAIL=$((FAIL + 1))
  fi
}

assert_fails() {
  local desc="$1"; shift
  if "$@" >/dev/null 2>&1; then
    echo "  NG: $desc (成功してしまった)"
    FAIL=$((FAIL + 1))
  else
    echo "  OK: $desc"
    PASS=$((PASS + 1))
  fi
}

# --- サンドボックス構築 ---------------------------------------------------
SANDBOX="$(mktemp -d)"
trap 'rm -rf "$SANDBOX"' EXIT

mkdir -p "$SANDBOX/scripts"
mkdir -p "$SANDBOX/src-tauri/gen/android/app"
cp "$TARGET_SCRIPT" "$SANDBOX/scripts/bump-version.sh"

cat > "$SANDBOX/package.json" <<'EOF'
{
  "name": "multi-column-x",
  "version": "0.1.2",
  "dependencies": {
    "react": "^19.1.0"
  }
}
EOF

cat > "$SANDBOX/src-tauri/tauri.conf.json" <<'EOF'
{
  "productName": "MultiColumnX",
  "version": "0.1.2",
  "identifier": "com.natsuyasai.multicolumnx"
}
EOF

cat > "$SANDBOX/src-tauri/Cargo.toml" <<'EOF'
[package]
name = "multicolumnx"
version = "0.1.2"
edition = "2021"

[dependencies]
tauri = { version = "2", features = ["devtools"] }
EOF

cat > "$SANDBOX/src-tauri/Cargo.lock" <<'EOF'
[[package]]
name = "other-crate"
version = "0.1.2"

[[package]]
name = "multicolumnx"
version = "0.1.2"
dependencies = [
 "tauri",
]
EOF

cat > "$SANDBOX/src-tauri/gen/android/app/tauri.properties" <<'EOF'
// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
tauri.android.versionName=0.1.0
tauri.android.versionCode=1000
EOF

# --- 正常系: 0.1.3 へ更新 -------------------------------------------------
echo "[テスト] 正常系: 0.1.3 へ一括更新"
bash "$SANDBOX/scripts/bump-version.sh" 0.1.3 >/dev/null

assert_contains "$SANDBOX/package.json" '"version": "0.1.3"' "package.json が更新される"
assert_contains "$SANDBOX/src-tauri/tauri.conf.json" '"version": "0.1.3"' "tauri.conf.json が更新される"
assert_contains "$SANDBOX/src-tauri/Cargo.toml" 'version = "0.1.3"' "Cargo.toml が更新される"
assert_contains "$SANDBOX/src-tauri/gen/android/app/tauri.properties" 'tauri.android.versionName=0.1.3' "Android versionName が更新される"
assert_contains "$SANDBOX/src-tauri/gen/android/app/tauri.properties" 'tauri.android.versionCode=1003' "Android versionCode が算出される (0.1.3 -> 1003)"

# Cargo.lock は multicolumnx だけ更新し、他クレートは据え置き
echo "[テスト] Cargo.lock は multicolumnx のみ更新"
if grep -qF 'name = "multicolumnx"' "$SANDBOX/src-tauri/Cargo.lock" \
   && awk '/name = "multicolumnx"/{getline; print}' "$SANDBOX/src-tauri/Cargo.lock" | grep -qF 'version = "0.1.3"'; then
  echo "  OK: multicolumnx の version が 0.1.3 に更新される"
  PASS=$((PASS + 1))
else
  echo "  NG: multicolumnx の version 更新に失敗"
  FAIL=$((FAIL + 1))
fi
if awk '/name = "other-crate"/{getline; print}' "$SANDBOX/src-tauri/Cargo.lock" | grep -qF 'version = "0.1.2"'; then
  echo "  OK: other-crate の version は据え置かれる"
  PASS=$((PASS + 1))
else
  echo "  NG: other-crate の version が誤って書き換えられた"
  FAIL=$((FAIL + 1))
fi

# --- 異常系: 不正なバージョン --------------------------------------------
echo "[テスト] 異常系: 不正な入力を拒否"
assert_fails "引数なしは失敗する" bash "$SANDBOX/scripts/bump-version.sh"
assert_fails "x.y 形式は失敗する" bash "$SANDBOX/scripts/bump-version.sh" 0.1
assert_fails "非数値は失敗する" bash "$SANDBOX/scripts/bump-version.sh" v1.2.3

# --- 集計 -----------------------------------------------------------------
echo ""
echo "結果: $PASS 件成功 / $FAIL 件失敗"
if [ "$FAIL" -ne 0 ]; then
  exit 1
fi
